INCLUDES += -I$(BINDIRBASE)/pkg/$(BOARD)
DIRS += $(BINDIRBASE)/pkg/$(BOARD)/fatfs

INCLUDES += -I$(RIOTBASE)/pkg/fatfs/fatfs_diskio/include

ifneq (,$(filter fatfs_diskio_native,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/fatfs/fatfs_diskio/native
endif

ifneq (,$(filter fatfs_diskio_sdcard_spi,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/fatfs/fatfs_diskio/sdcard_spi
endif

ifeq ($(shell uname -s),Darwin)
    CFLAGS += -Wno-empty-body
endif
