# define the cpu used by the nucleo144-f446 board
export CPU = stm32f4
export CPU_MODEL = stm32f446ze

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
